// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADnlGNYm4Hg-Rh8GONm06ZkosYhp3xnHE',
    appId: '1:447955597401:web:20c4f8f6dcf04c84f49948',
    messagingSenderId: '447955597401',
    projectId: 'sheet-eed3c',
    authDomain: 'sheet-eed3c.firebaseapp.com',
    storageBucket: 'sheet-eed3c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_F6n9hG2zdpdY--6C1hw4MjxHLAgvofM',
    appId: '1:447955597401:android:daced6b62c3bb155f49948',
    messagingSenderId: '447955597401',
    projectId: 'sheet-eed3c',
    storageBucket: 'sheet-eed3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAKDySw5mEdqjqfhBlD-Z5FLK4VD0MfvM',
    appId: '1:447955597401:ios:09ab3c84debddbdbf49948',
    messagingSenderId: '447955597401',
    projectId: 'sheet-eed3c',
    storageBucket: 'sheet-eed3c.appspot.com',
    iosClientId: '447955597401-an5fc8h2gmv996fho2ah182fr4t8nfrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAKDySw5mEdqjqfhBlD-Z5FLK4VD0MfvM',
    appId: '1:447955597401:ios:09ab3c84debddbdbf49948',
    messagingSenderId: '447955597401',
    projectId: 'sheet-eed3c',
    storageBucket: 'sheet-eed3c.appspot.com',
    iosClientId: '447955597401-an5fc8h2gmv996fho2ah182fr4t8nfrs.apps.googleusercontent.com',
    iosBundleId: 'com.example.sheet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyADnlGNYm4Hg-Rh8GONm06ZkosYhp3xnHE',
    appId: '1:447955597401:web:5a0a24204c101760f49948',
    messagingSenderId: '447955597401',
    projectId: 'sheet-eed3c',
    authDomain: 'sheet-eed3c.firebaseapp.com',
    storageBucket: 'sheet-eed3c.appspot.com',
  );

}